<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'AddPunctuationLinter' => 'linter/AddPuncutationLinter.php',
    'CapitalizeLineLinter' => 'linter/CapitalizeLineLinter.php',
    'CustomArcanistLintEngine' => 'linter/CustomArcanistLintEngine.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'AddPunctuationLinter' => 'ArcanistLinter',
    'CapitalizeLineLinter' => 'ArcanistLinter',
    'CustomArcanistLintEngine' => 'ArcanistLintEngine',
  ),
));
